### ISSUE TITLE
Phone call support

### ISSUE THREAD

**Issue by adminy** [kiki-kanri/kikiutils-node-modem-manager#1]
I have heard that modem manager is capable of making and receiving phone calls.

Any plans to add that part of the API?

Also I noticed you have 5G as a network option. What modem do you use to have 5G?

**Comment by kiki-kanri** [comment]
Yes, the modem manager can indeed make and receive calls, but since I am using a linux system (ubuntu 22.04) and I don’t know how to connect audio devices to the modem manager, so there is currently no plan to add this api.

Relevant command operations are at the URL https://www.freedesktop.org/software/ModemManager/man/latest/mmcli.1.html VOICE OPTIONS and CALL OPTIONS area.

If you have found and tested the method of connecting audio devices, you can provide it to me, and I will try to add the phone calls apis.

Finally, although there are 5G options in some places but I don’t actually have a 5G device.
This 5G-related option was added when I saw the mmcli command output and modem manager documents.

If you have any questions, welcome to ask again, thank you!
